version: '3.8'
services:
  app:
    image: ebook-price:latest
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - ./src:/app/src
    networks:
      - ebook-price
    depends_on:
      - cache
      - db

  db:
    image: postgres:16
    container_name: ebook_price_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    networks:
      - ebook-price

  cache: 
    image: redis:latest
    container_name: cache-redis
    ports:
      - '6379:6379'
    networks:
      - ebook-price

networks:
  ebook-price: